### PR TITLE
Restructure and protect routes

### LINKED ISSUE #21: Protect routes
### Protect route

Add route protection and redirecting

**Difficulty**: Medium

**Priority**: High

### PR DESCRIPTION
**Pull request by Drewbi**
Fixes #21 

Protected routes and restructured frontend

### CODE REVIEW

**Comment by khattakdev** [comment]
@Drewbi What if you change `Pages` Structure to something like this
```
/Pages
  /Expert
    index.js
    index.module.css
  /Fallback
    index.js
    index.module.css
...
```

This will help us not populating `Pages` too much by adding individual *.module.css, neither we will have to add one single .css file where we put all the CSS/SASS for 4 - 5 pages.

**Comment by Drewbi** [comment]
@eKhattak Was definitely thinking about doing that. I'll add it now.

**Comment by khattakdev** [comment]
> @eKhattak Was definitely thinking about doing that. I'll add it now.
Here's an example
image

**Comment by Drewbi** [comment]
@eKhattak Yep.

**Comment by khattakdev** [comment]
> > @eKhattak Was definitely thinking about doing that. I'll add it now.

 Here's an example
image

**Comment by Drewbi** [comment]
@eKhattak That sure is an example alright 0:

**Review by khattakdev — CHANGES_REQUESTED** [review]
Looks Good!

**Review by khattakdev — APPROVED** [review]
Let's Merge!

**Pull request merged**
